name: update csvs

on:
  schedule: 
    - cron: '0 0 * * 6,0' # Runs at 00:00 every saturday and sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          DATABASE: ${{ secrets.DATABASE }}
          HOST: ${{ secrets.HOST }}
          CONN_STRING: ${{ secrets.CONN_STRING }}
          PASSWORD: ${{ secrets.PASSWORD}}
          USER: ${{ secrets.USER }}
          
        run: python ./Updating_with_BS4/to_csvs.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
